### ISSUE TITLE
Can I build Tesse-simulator from the source ?

### ISSUE THREAD

**Issue by han-kyung-min** [MIT-TESSE/tesse-example-project#1]
Hello
Thanks for the nice simulator.

This might be a dumb question since I am new to Unity..
I am trying to build Tesse scenes from the source in order to take images of the entire building from different view points. I assume that "tesse-example-project" is the one I should try to do so, correct ?

But, when I try to run "git clone --recurse-submodules git@github.mit.edu:TESS/tesse-example-project.git"

I get an error message below:

```
_Cloning into 'tesse-example-project'...
git@github.mit.edu: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
This is weird since I followed the instruction in GitHub page to add ssh-key in my account.

Does it mean that I don't have a permisson to build Tesse simulator from the source ?

Thanks for your help in advance.

**Comment by han-kyung-min** [comment]
Well, if I clone "tesse-example-project" then clone "tesse-core" in tesse-example-project/Assets/ then rename "tesse-core" to TESSE. I can open the project. But, there is only a robot in an empty space (without the building).

**Comment by han-kyung-min** [comment]
Never mind. Someone asked the same question before...  https://github.com/MIT-TESSE/goseek-challenge/issues/32

**Comment by ZacRavichandran** [comment]
Hi @thezest76, I'm glad you find the simulator useful! 

The permission denied error was due to a link that mistakenly pointed to our internal repo (`git@github.mit.edu` instead of `git@github.com`). I updated the link, but it sounds like you were able to build the project anyway. 

As discussed in the issue referenced above, we're unable to release the scenes due to licensing conflicts. We do still intend to open-source our own assets and scenes. Those are currently in development, and we plan to release them within the next few months.
